// Generated by CoffeeScript 1.12.4
(function() {
  var SimpleChat, myChatApp;

  SimpleChat = (function() {
    var fireBase;

    fireBase = new Firebase("https://simplechatapp.firebaseio.com/");

    function SimpleChat() {
      fireBase.on("child_added", (function(_this) {
        return function(snapshot) {
          var message;
          message = snapshot.val();
          return _this.messagesView(message.name, message.text);
        };
      })(this));
      $("#newMessage input").keypress((function(_this) {
        return function(e) {
          var name, text;
          if (e.keyCode === 13) {
            name = $("#newMessage input[name='name']").val();
            text = $("#newMessage input[name='text']").val();
            $("#newMessage input[name='text']").val("");
            return _this.newMessage(name, text);
          }
        };
      })(this));
    }

    SimpleChat.prototype.messagesView = function(name, text) {
      var listItem, nameItem, textItem;
      listItem = jQuery("<li/>");
      nameItem = jQuery("<p/>", {
        "class": "name",
        text: name
      });
      textItem = jQuery("<p/>", {
        "class": "text",
        text: text
      });
      listItem.appendTo("#listMessages ul");
      nameItem.appendTo(listItem);
      return textItem.appendTo(listItem);
    };

    SimpleChat.prototype.newMessage = function(name, text) {
      return fireBase.push({
        name: name,
        text: text
      });
    };

    return SimpleChat;

  })();

  myChatApp = new SimpleChat;

}).call(this);
